---
abstract: 'Match incompletely specified bases in nucleic acid sequences'
author:
  - 'Leon Timmermans <leont@cpan.org>'
build_requires:
  File::Spec: 0
  IO::Handle: 0
  IPC::Open3: 0
  Test::Deep: 0
  Test::Exception: 0
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300038, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Bio-DNA-Incomplete
provides:
  Bio::DNA::Incomplete:
    file: lib/Bio/DNA/Incomplete.pm
    version: 0.004
requires:
  Carp: 0
  Sub::Exporter::Progressive: 0
  perl: 5.006
  strict: 0
  warnings: 0
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Bio-DNA-Incomplete
  repository: git://github.com/Leont/bio-dna-incomplete.git
version: 0.004
